name: Hub Deploy

on:
  push:
    branches: [main]
    paths:
      - 'apps/hub/**'
      - 'packages/**'
      - '.github/**'
      - 'scripts/**'
      - 'package.json'

jobs:
  deploy-hub:
    uses: ./.github/workflows/reuseable-deploy.yml
    with:
      app_name: hub
    secrets: inherit
